---
# handlers file for deploy_apache_web
- name: Restart apache centos
  service: name=httpd state=restarted
  when: ansible_os_family == "RedHat"

- name: Restar apache Ubuntu
  service: name=apache2 state=restarted
  when: ansible_os_family == "Debian"
