---
# tasks file for deploy_apache_web
- block: #====== for RedHat

    - name: Install Apache Centos
      yum: name=httpd state=latest

    - name: Start Apache it on enable the every boot
      service: name=httpd state=started enabled=yes

  when: ansible_os_family == "RedHat"


- block:

    - name: Install Apache to Ubuntu
      apt: name=apache2 state=latest

    - name: Start Apache it on enable the every boot
      service: name=apache2 state=started enabled=yes

  when: ansible_os_family == "Debian"

- name: Generated j2 file
  template: src=index.j2 dest={{ destin_folder }}/index.html mode=0555
